
SPELL_LOOKUP = {
    0: "None",
    1: "Wand",
    2: "BowAndArrow",
    3: "Broadsword",
    4: "Hourglass",
    5: "Calm",
    6: "Feather",
    7: "RingsOfFire",
    8: "Firestorm",
    9: "GoldNecklace",
    10: "Hammer",
    11: "JadeAmulet",
    12: "Joust",
    13: "JadeRing",
    14: "Dagger",
    15: "LeatherBook",
    16: "EnergyOrb",
    17: "Noise",
    18: "OpalAmulet",
    19: "Pyros",
    20: "RoarStick",
    21: "ShortAxe",
    22: "Trident",
    23: "TurquoiseRing",
    24: "Boomerang",
    25: "UnusedSpellId25",

    50: "DeveloperMistake_VialOfWinds",
    42: "DeveloperMistake_Raft",
    99: "ZeldaWeakness_99_maybe"
}

TREASURE_LOOKUP = {
    0: "NoneOrVialOfAcid",
    1: "AlligatorShoes",
    2: "BrownJar",
    3: "BlackOrb",
    4: "Bone",
    5: "Bouquet",
    6: "Brush",
    7: "Ticket_BlueGreenKnights",
    8: "Candle",
    9: "RawSteak",
    10: "Coal",
    11: "Compass1",
    12: "Compass2",
    13: "Compass3",
    14: "Compass4",
    15: "Compass5",
    16: "Compass6",
    17: "Compass7",
    18: "Diamond",
    19: "EmptyWaterBottle",
    20: "Flute",
    21: "FullWaterBottle",
    22: "Plank",
    23: "Knife",
    24: "GoldTrumpet",
    25: "Harp",
    26: "Ticket_RedKnight",
    27: "LifePotion",
    28: "Map1",
    29: "Map2",
    30: "Map3",
    31: "Map4",
    32: "Map5",
    33: "Map6",
    34: "Map7",
    35: "Rug",
    36: "MagicShield",
    37: "FishingNet",
    38: "Ladder",
    39: "WhiteOrb1",
    40: "WhiteOrb2",
    41: "Saltcellar",
    42: "Raft",
    43: "RedBoots",
    44: "Repellent",
    45: "RedBow",
    46: "RupeeItem",
    47: "Scroll",
    48: "WoodenSpoon",
    49: "SilverTrumpet",
    50: "VialOfWinds",
    51: "GoldenBoots"
}

DIRECTION_LOOKUP = {
    0: "UP",
    1: "RIGHT",
    2: "DOWN",
    3: "LEFT",
    4: "TELEPORT"
}